<a href="https://colab.research.google.com/github/Kornel1156/Data-Science/blob/main/6_Uczenie_Maszynowe_scikit-learn/02_metryki_klasyfikacja.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### scikit-learn

Metryki pozwalaja ocenic czy dany model jest dobry czy tez nie jest dobry

>Strona biblioteki: [https://scikit-learn.org](https://scikit-learn.org)  
>
>Dokumentacja/User Guide: [https://scikit-learn.org/stable/user_guide.html](https://scikit-learn.org/stable/user_guide.html)
>
>Podstawowa biblioteka do uczenia maszynowego w języku Python.
>
>Aby zainstalować bibliotekę scikit-learn, użyj polecenia poniżej:
```
pip install scikit-learn
```
### Metryki - Problem klasyfikacji:
1. [Import bibliotek](#a0)
2. [Metryki - Klasyfikacja binarna](#a1)
    1. [Accuracy - dokładność klasyfikacji](#a2)
    2. [Macierz konfuzji/pomyłek](#a3)
    3. [Krzywa ROC](#a4)
3. [Metryki - Klasyfikacja wieloklasowa](#a5)  tutaj klasygikacji binarna nie zadziała tutaj wejdzie klasyfikacja krzywa ROC
    1. [Accuracy - dokładność klasyfikacji](#a6)
    2. [Macierz konfuzji/pomyłek](#a7)
    3. [Raport klasyfikacji](#a8)

#### <a name='a0'></a> Import bibliotek

In [1]:
# import bibliotek oraz
import numpy as np
import pandas as pd
# plotly biblioteka z interaktywnymi wykresami w przeciwienstwie do matplotlib
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots # funkcja make_subplots do wizualizacji

#### <a name='a1'></a>  Metryki - Klasyfikacja binarna , czyli taka w której mamy do przewidzenia 2 klasy , np ocena zdolnosci kredytowej w banku , oraz sytuacji czy klient odejdzie od nas w najblizszym czasie , czy tez zdjecia gdzie mamy koty oraz psy  
#### <a name='a2'></a> Accuracy - Dokładność klasyfikacji

correct prediction - poprawne predycje(przypisan) klas modelu dla danych

total predictions - przez poprawna liczbe predykcji(przypisan) klas model dla danych  

####   $$Accuracy = \frac{correct\ predictions }{total\ predictions} * 100$$

In [2]:
# na sztywno tworzymy 2 zmienne które normalnie były by wynikami w naszych danych oraz wynikami ktore przupisał czyli predyckji wyuczonego modelu

# parametr z klasami ktore sa prawdziwe
y_true = np.array([1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1])
# parametr z klasami ktore nasz model przwidział ( widac ze dla paru obiektow sie pomylił )
y_pred = np.array([0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1])

In [3]:
# importujemy biblioteke z gotowa funkcja ktora pozwala na uzycie metryki
from sklearn.metrics import accuracy_score

# metryka - dokładnosc predykcji przewidzenia poprawnosci przypisanych klas do obiektow
accuracy_score(y_true, y_pred)

#
# Wynik to 80% poprawnosci przypisanych klas do obiektow

0.8

In [4]:
# obietk dataFrame który bedzie zawierał obiekty y_true oraz y_pred
results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred}) # tworzymy słownik z tych danych
results

    y_true  y_pred
0        1       0
1        0       0
2        1       1
3        1       1
4        0       0
5        1       1
6        1       0
7        0       0
8        1       1
9        0       1
10       1       0
11       1       1
12       0       0
13       1       1
14       1       1
15       0       0
16       1       0
17       1       1
18       0       0
19       1       1
20       1       1
21       1       1
22       0       1
23       1       1
24       1       1
25       0       0
26       1       1
27       1       1
28       0       0
29       1       1

In [5]:

# wykorzystujac DataFrame czyli podstawowego obiektu w bibliorece plotly wykonamy na nim wizualizacje danych

# sortuajemy dane po (by) zmienne y_true
results = results.sort_values(by='y_true')

# reset_index - resetuje nam index
results = results.reset_index(drop=True)

# tworzymy kolumne sample z indexem powiekszonym o wartosc 1
results['sample'] = results.index + 1
results

    y_true  y_pred  sample
0        0       0       1
1        0       0       2
2        0       0       3
3        0       1       4
4        0       0       5
5        0       0       6
6        0       1       7
7        0       0       8
8        0       0       9
9        0       0      10
10       1       1      11
11       1       1      12
12       1       0      13
13       1       1      14
14       1       1      15
15       1       0      16
16       1       1      17
17       1       1      18
18       1       0      19
19       1       1      20
20       1       1      21
21       1       1      22
22       1       1      23
23       1       0      24
24       1       1      25
25       1       1      26
26       1       1      27
27       1       1      28
28       1       1      29
29       1       1      30

In [6]:
# towrzymy obiekt fig z metpda make_subplots do wizualizacji obiektow poprawnych oraz tych przewidzianych przez model
fig = make_subplots(rows=2, cols=1) # 2 wiersze oraz 1 kolumna

#  dodajemy funkcje add_trace czyli slad naszego wykresu oraz go.Satter czyli wukres punktowy
 # x = numer próbki , y = prawdziwe etykiety , oraz nazwe i miejsce w okienku
fig.add_trace(go.Scatter(x=results['sample'], y=results['y_true'], mode='markers', name='y_true'), row=1, col=1)
# x = numer próbki , y = przypuszczone etykiety przez model , oraz nazwe i miejsce w okienku
fig.add_trace(go.Scatter(x=results['sample'], y=results['y_pred'], mode='markers', name='y_pred'), row=2, col=1)
# aktualizujemy nasz layout na szerokosc i wysokoosc oraz podajemy tytuł layoutu
fig.update_layout(width=900, height=500, title='Klasyfikator binarny')

# wyswietlamy layout
fig.show()

# mozemy w ten sposob przedstawic  jak nasz model dobie radzi
# pierwszy layout przedstawia to jakie sa poprawne klasy
# drugi layout przedstawia to jakie klasy przyporzadkował nam model po naucze

# jak widac mamy 6 błednych przypasowań

#### <a name='a3'></a> Macierz konfuzji/pomyłek

In [7]:
# importujemy metode confusion_matrix która nam oceni model poprzez macierz konfuzji
from sklearn.metrics import confusion_matrix

# piniewaz mamy tylko problem 2 klasami , gdybysmy mieli wiecej klas to byśmy mieli liczba_klas razy liczba_klas

# tutaj kazdy wiersz to jedna klasa i na przekatnej pojawia sie wynik ile klas zostało przypisanych do danego wiersza wiec maksymalizujemy ilosc na przekatnych
confusion_matrix(y_true, y_pred)

# w wyniku widzimy ze tylko 8 obiektow na 10 zostalo poprwnie przypisancyh i tylko 16 na 20 zostało przypisanych do wiersza 2

array([[ 8,  2],
       [ 4, 16]])

In [10]:
# ale zwizualizujmy sobie przykład macierzy konfuzji
import plotly.figure_factory as ff

def plot_confusion_matrix(cm):
    cm = cm[::-1] # funckja potrzebuje od konca wartosci z macierzy konfuzji
    # wymaga zeby to był obiekt dataFrame
    cm = pd.DataFrame(cm, columns=['pred_0', 'pred_1'], index=['true_1', 'true_0'])

    # korzystamy z wykresu ff.create_annotated_heatmap
    fig = ff.create_annotated_heatmap(z=cm.values, x=list(cm.columns), y=list(cm.index), colorscale='ice', showscale=True, reversescale=True)
    # aktualizacja oraz rozmiary
    fig.update_layout(width=400, height=400, title='Confusion Matrix', font_size=16)
    fig.show()

cm = confusion_matrix(y_true, y_pred)

# wykonujmey
plot_confusion_matrix(cm)

# wynik model przewidział
# true_0 w 8 przypadkach dobrze oraz w 2 sie pomylił
# true_1 w 16 przypadkach dobrze oraz w 4 sie pomylił

In [11]:
# jakie metryki możemy na podstawie macierzy konfuzji wyznaczyć

# metoda ravel pozwala rozwinac nasz tablice i dostać wartosc w postaci jednowymiatowej tablicy numpy
tn, fp, fn, tp = cm.ravel()


# true-negative , false-positive , false-negative , true-positive

# true-negative czyli prawdziwie przewidzielismy klase negatywną , pred_0 - negatywne przewidzeni klasy , pred_1 - pozytywne przewidzenie klasy
# false-positive mielismy klase pred_0 a fałszywie przewidzielosmy klase1 pred_1  , kwadrat prawy gorny
# false-negative true_1 klasa pozytywna i fałszywie przewidzielismy klase negatywna , kwadrat lewy dolny
# true-positive mielismy klase pozytywna pred_1 przewidzielismy klase pozytywna


print(f'TN - True Negative: {tn}')
print(f'FP - False Positive: {fp}')
print(f'FN - False Negative: {fn}')
print(f'TP - True Positive: {tp}')

TN - True Negative: 8
FP - False Positive: 2
FN - False Negative: 4
TP - True Positive: 16

4 METRYKI

In [12]:
# 1 METRYKA - BŁAD PIERWSZEGO RODZAJU - Type I error lub false positive rate

# Type I error - False Positive Rate
fpr = fp / (fp + tn)

# wskaznik wartosci fałszywie-pozytywnych
fpr

# wynik to 20% pomyłki w przypisaniu 1 klasy dla na wszystkich obiektach

np.float64(0.2)

In [13]:
# Type II error - False Negative Rate
fnr = fn / (fn + tp)
fnr

# interpretacja
# czyli 4 przypadki na 20 obiektow zostało blednie przypisane im klasy

np.float64(0.2)

In [14]:
# Precision - ile obserwacji przewidywanych jako pozytywne są w rzeczywistości pozytywne
precision = tp / (tp + fp)
print(precision)

#Spośród wszystkich 18 obiektów, które model zaklasyfikował jako pozytywne, 16 faktycznie należało do tej klasy (88.89%)
# , a 2 zostały zaklasyfikowane błędnie (były w rzeczywistości negatywne).

0.8888888888888888

In [15]:
# Recall - jak wiele obserwacji z wzystkich poytywnych sklasyfikowaliśmy jako pozytywne
recall = tp / (tp + fn)


print(recall)

# interpretacja
# Recall - spośród wszystkich 10 rzeczywiście pozytywnych obiektów
# model poprawnie sklasyfikował 8 jako pozytywne (80%).
# Pozostałe 2 były pozytywne, ale model sklasyfikował je jako negatywne.

0.8

#### <a name='a4'></a> Krzywa ROC

In [ ]:
from sklearn.metrics import roc_curve

fpr, tpr, thresh = roc_curve(y_true, y_pred, pos_label=1)
roc = pd.DataFrame({'fpr': fpr, 'tpr': tpr})
roc

In [ ]:
def plot_roc_curve(y_true, y_pred):
    # Binary classification
    from sklearn.metrics import roc_curve
    fpr, tpr, tresh = roc_curve(y_true, y_pred, pos_label=1)

    fig = go.Figure(data=[go.Scatter(x=roc['fpr'], y=roc['tpr'], line_color='red', name='ROC Curve'),
                        go.Scatter(x=[0, 1], y=[0, 1], mode='lines', line_dash='dash', line_color='navy')],
                    layout=go.Layout(xaxis_title='False Positive Rate',
                                    yaxis_title='True Positive Rate',
                                    title='ROC Curve',
                                    showlegend=False,
                                    width=800,
                                    height=400))
    fig.show()
plot_roc_curve(y_true, y_pred)

#### <a name='a5'></a> Metryki - Klasyfikacja wieloklasowa

#### <a name='a6'></a> Accuracy - Dokładność klasyfikacji

####   $$Accuracy = \frac{correct\ predictions}{total\ predictions} * 100$$

In [ ]:
y_true = np.array([1, 0, 1, 2, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1, 1, 2, 2, 1, 0, 1, 1, 0, 2, 1, 1, 2, 2])
y_pred = np.array([0, 0, 1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 1, 1, 1, 2, 2])

accuracy_score(y_true, y_pred)

#### <a name='a7'></a> Macierz konfuzji/pomyłek

In [ ]:
cm = confusion_matrix(y_true, y_pred)
cm

In [ ]:
def plot_confusion_matrix(cm):
    cm = cm[::-1]
    cm = pd.DataFrame(cm, columns=['pred_0', 'pred_1', 'pred_2'], index=['true_2','true_1', 'true_0'])

    fig = ff.create_annotated_heatmap(z=cm.values, x=list(cm.columns), y=list(cm.index),
                                      colorscale='ice', showscale=True, reversescale=True)
    fig.update_layout(width=400, height=400, title='Confusion Matrix', font_size=16)
    fig.show()

plot_confusion_matrix(cm)

#### <a name='a8'></a> Raport klasyfikacji

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred))

In [ ]:
print(classification_report(y_true, y_pred, target_names=['label_1', 'label_2', 'label_3']))