<a href="https://colab.research.google.com/github/Kornel1156/Data-Science/blob/main/2_Pandas_Analiza_Danych/01_biblioteka_pandas_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Spis Treści
# Podstawowe Struktury Danych w Pandas
1. [pd.Series](#scrollTo=Series)
2. [pd.DataFrame](#scrollTo=DataFrame)
2. [Selekcja kolumn](#scrollTo=Selekcja_kolumn)

instalacja biblioteki Pandas

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

Import biblioteki

In [ ]:
import pandas as pd
pd.__version__

'2.2.2'

Aby dane zostaly zapisane w przeciwienstwie do biblioteki Numpy w Pandas trzeba przypisac je do zmiennej bo np w Numpy w funkcji shuffle nie trzeba przypisywac a w Pandas trzeba przypisac do zmiennej zeby sie zapisalo

# Series

In [ ]:
# tworzymy obiekt za pomoca funkcji Series , który automatycznie przyporzdkowywuje indeksy wierszy oraz kolumn
s = pd.Series([3, 2, 4 , 6 ] )
s

0    3
1    2
2    4
3    6
dtype: int64

In [ ]:
# dodanie parametru ktory bedzie przyporzadkowywał wierszom nadane indexy
s = pd.Series([3, 2, 4 , 6 ] , index = ['a', 'b', 'c', 'd' ] )
s

a    3
b    2
c    4
d    6
dtype: int64

In [ ]:
# dodanie parametru ktory bedzie przyporzadkowywał wierszom nadane indexy oraz nazwe naszej serii danych
s = pd.Series([3, 2, 4 , 6 ] , index = ['a', 'b', 'c', 'd' ] , name='nazwa_serii_danych' )
s

a    3
b    2
c    4
d    6
Name: nazwa_serii_danych, dtype: int64

In [ ]:
# dostosowanie typu danych do podanego jak w numpy wszystkie musza miec ten sam typ danych
# jesli podamy rozne dane to seria przyjmie typ danych object
s = pd.Series([3., 2, 4 , 6 ] , index = ['a', 'b', 'c', 'd' ] )
s

a    3.0
b    2.0
c    4.0
d    6.0
dtype: float64

! ! ! BRAKI DANYCH ! ! !  
jak sobie z nimi poradzić ?
w tym celu wykorzystujemy biblioteke numpy trzeba ja zaimportować

In [ ]:
import numpy as np

specjalny atrybut w bibliotece numpy który pozwala na przedstawianie brakujacych danych jako typ np.nan - określa brakujace dane

In [ ]:
np.nan

nan

In [ ]:
# seria ze wstawionym typem przedstawiajacym brakujaca wartosc danych jako nan
s = pd.Series([3., np.nan, 4 , 6 ] , index = ['a', 'b', 'c', 'd' ] )
# brak wartosc w wierszu b
s

a    3.0
b    NaN
c    4.0
d    6.0
dtype: float64

In [ ]:
# obiekt series składający sie z danych typu bool
s = pd.Series(data=[True , False , True ])
s

0     True
1    False
2     True
dtype: bool

In [ ]:
# uzywanie danych i dzialanie z binlioteka dla danych czasowych z szeregami czasowymi itd czasem
# generowanie wartosci od 10 do 19 włacznie bez 20 | generujemy daty poczawszy od rok 2020-01-01 | parametr periods czyli ilosc dni od tego dnia
s = pd.Series(data=np.arange(10, 20) , index=pd.date_range(start='20200101' , periods=10))
s

2020-01-01    10
2020-01-02    11
2020-01-03    12
2020-01-04    13
2020-01-05    14
2020-01-06    15
2020-01-07    16
2020-01-08    17
2020-01-09    18
2020-01-10    19
Freq: D, dtype: int64

In [ ]:
#indeksy
s.index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
list(s.index)

[Timestamp('2020-01-01 00:00:00'),
 Timestamp('2020-01-02 00:00:00'),
 Timestamp('2020-01-03 00:00:00'),
 Timestamp('2020-01-04 00:00:00'),
 Timestamp('2020-01-05 00:00:00'),
 Timestamp('2020-01-06 00:00:00'),
 Timestamp('2020-01-07 00:00:00'),
 Timestamp('2020-01-08 00:00:00'),
 Timestamp('2020-01-09 00:00:00'),
 Timestamp('2020-01-10 00:00:00')]

In [ ]:
# typ danych
s.dtypes

dtype('int64')

In [ ]:
# obiekt typu series który bedzie zawieral dane tekstowe
s = pd.Series(data=['java' , 'python' , 'c++' , 'sql'] , name='languages')
s

0      java
1    python
2       c++
3       sql
Name: languages, dtype: object

In [ ]:
# typ obiektu
type(s)

pandas.core.series.Series

In [ ]:
# indeksy danych
s.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
# wartosci
s.values

array(['java', 'python', 'c++', 'sql'], dtype=object)

In [ ]:
# atrybut dtype podaje typ danych skrót od O to Object
s.dtypes

dtype('O')

In [ ]:
# obiekt zawierajace infromacje o cenie notowana trzech społek ale jako slownik poprzez {} a nie liste []
price = pd.Series(data={'Apple' : 200 , 'CD Projekt' : 60 , 'Amazon' : 1900 })
price

Apple          200
CD Projekt      60
Amazon        1900
dtype: int64

In [ ]:
# wycinanie interesujacych danych ze danych
price['CD Projekt']

np.int64(60)

In [ ]:
# 2 sposob na wyciagniecie wartosci z tabeli danych obiektu poprzez obiekt.iloc[index] lub po prostu obiekt price[1]
print(price[1])
print(price.iloc[1])

60
60

/tmp/ipykernel_1768/2758806400.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(price[1])

In [ ]:
#zliczanie liczby elementow w naszym obiekcie
price.count()

np.int64(3)

In [ ]:
# funkcja value_counts() sprawdza ilosc wystapien poszczegolnych wartosci elementow w tabeli inaczej przedstawia rozklad , niezbedny np dla histogramu
price.value_counts()

200     1
60      1
1900    1
Name: count, dtype: int64

Funkcje rowniez wystepujace w NumPy oraz w Pandas

In [ ]:
# funkcja sumujaca wartosci
price.sum()

np.int64(2160)

In [ ]:
# max oraz min
print(price.min())
print(price.max())

60
1900

In [ ]:
# odchylenie standardowe
price.std()

1024.3046421841502

In [ ]:
# funkcja opisujaca obiekt zbiorczo przedstawiajaca statystyki
# ilosc , srednia , odchylenie . minimum , kwantyle rozkladu czyli 1/4 1/2 3/4 oraz max
price.describe()

count       3.000000
mean      720.000000
std      1024.304642
min        60.000000
25%       130.000000
50%       200.000000
75%      1050.000000
max      1900.000000
dtype: float64

In [ ]:
# dodajmy sobie index ktory nie ma wartosci
price = pd.Series(data={'Apple' : 200 , 'CD Projekt' : 60 , 'Amazon' : 1900 , 'KGHM'  : np.nan })
price

Apple          200.0
CD Projekt      60.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [ ]:
# count nie uwzgledni tej danej
price.count()

np.int64(3)

In [ ]:
# wartoc tez nie zostanie uwzgledniona chyba ze ustawimy parametr dla funkcji dropna to wtedy zostana braki danych uwzglednione
price.value_counts(dropna=False)

200.0     1
60.0      1
1900.0    1
NaN       1
Name: count, dtype: int64

In [ ]:
#funkcja do wyciagania indexow z najwiekszymi wartosciami *.nlargest(ilosc najwiekszych wartosci)
price.nlargest(2)

Amazon    1900.0
Apple      200.0
dtype: float64

In [ ]:
#funkcja do wyciagania indexow z najmniejszymi wartosciami *.nsmallest(ilosc najmniejszymi wartosci)
price.nsmallest(2)

CD Projekt     60.0
Apple         200.0
dtype: float64

In [ ]:
# funkcja uporzadkowywujaca dane w tabeli
price.rank()

Apple         2.0
CD Projekt    1.0
Amazon        3.0
KGHM          NaN
dtype: float64

In [ ]:
# funkcja sortujaca indexy
price.sort_index()

Amazon        1900.0
Apple          200.0
CD Projekt      60.0
KGHM             NaN
dtype: float64

In [ ]:
# funkcja sortujaca po wartosciach
price.sort_values()

CD Projekt      60.0
Apple          200.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [ ]:
# chcac zmienic kolejnosc sortowania z domyslnego rosnacego to ustawiamy parametr ascending=False
price.sort_values(ascending=False)

Amazon        1900.0
Apple          200.0
CD Projekt      60.0
KGHM             NaN
dtype: float64

In [ ]:
# metoda apply ktora przyjmue jako pierwszy parametr funkcje  , wybieramy lambda i mnozemy kazdy z elementow przez 3.8 na złotowki
price_pln  = price.apply(lambda x : x * 3.8)
price_pln

Apple          760.0
CD Projekt     228.0
Amazon        7220.0
KGHM             NaN
dtype: float64

# DataFrame

In [ ]:
# utworzenie najbardziej używanego obiektu w analityce czyli ramki danych
df = pd.DataFrame(data=[12, 12 ,32])
df

    0
0  12
1  12
2  32

In [ ]:
# rozwiniecie naszej tabeli danych o nazwy wierszy oraz nazwe jedynej kolumny dla danych akutalnie
df = pd.DataFrame(data=[12, 12 ,32] , index=['first' , 'second' , 'third'] , columns=['col_1'])
df

        col_1
first      12
second     12
third      32

In [ ]:
# utworzenie
df = pd.DataFrame(data={'WIG20' : ['PKN ORLEN' , 'PKO BP'],
                        'MWIG40' : ['Amica' , 'Playway']})
df

       WIG20   MWIG40
0  PKN ORLEN    Amica
1     PKO BP  Playway

In [ ]:
# kolejne dane z parametrami tabeli
df = pd.DataFrame(data=[[10,12,13] , [23 ,12 ,10]] , index = ['first' , 'second' ] , columns=['col_1' ,'col_2' ,'col_3' ])
df

        col_1  col_2  col_3
first      10     12     13
second     23     12     10

In [ ]:
# nazwy kolumn ramki danych
df.columns

Index(['col_1', 'col_2', 'col_3'], dtype='object')

In [ ]:
# wiersze obiektu ramki danych
df.index

Index(['first', 'second'], dtype='object')

In [ ]:
# wartosci ramki danych
df.values

array([[10, 12, 13],
       [23, 12, 10]])

In [ ]:
# informacje obiektu
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, first to second
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col_1   2 non-null      int64
 1   col_2   2 non-null      int64
 2   col_3   2 non-null      int64
dtypes: int64(3)
memory usage: 172.0+ bytes

In [ ]:
# metoda opisujaca z gama statystyk
df.describe()
# ilosc rozncyh  , srednia , odchylenie standardowe , minimalan wartosc , kwantyle rozkladu 1/4 , 1/2 , 3/4 oraz wartosc maksymalna

           col_1  col_2     col_3
count   2.000000    2.0   2.00000
mean   16.500000   12.0  11.50000
std     9.192388    0.0   2.12132
min    10.000000   12.0  10.00000
25%    13.250000   12.0  10.75000
50%    16.500000   12.0  11.50000
75%    19.750000   12.0  12.25000
max    23.000000   12.0  13.00000

In [ ]:
# mozemy dokonaj transponowania ramki danych dla obiektu dataframe w pandas poprzez :
df.describe().T

       count  mean       std   min    25%   50%    75%   max
col_1    2.0  16.5  9.192388  10.0  13.25  16.5  19.75  23.0
col_2    2.0  12.0  0.000000  12.0  12.00  12.0  12.00  12.0
col_3    2.0  11.5  2.121320  10.0  10.75  11.5  12.25  13.0

# Selekcja kolumn inaczej selekcja zmiennych

In [ ]:
# przedstawienie ramki danych
df

        col_1  col_2  col_3
first      10     12     13
second     23     12     10

In [ ]:
# WYPISANIE WARTOSCI KOLUMNY popularnym elementem do wycinania w pythonie jest nawias kwadratowy []
# wybieramy jedną kolumne
df['col_1']

first     10
second    23
Name: col_1, dtype: int64

obiekt dataFrame moze miec kilkanascie typow z ktorych jest zrobiona bo składa sie miedzy innymi z typu Series

In [ ]:
type(df['col_1']) # tyo danych = pandas.core.series.Series

pandas.core.series.Series

In [ ]:
# wycinanie jednej komorki z calej tabeli
df

        col_1  col_2  col_3
first      10     12     13
second     23     12     10

In [ ]:
# chcac wyciąć kulumne używamy notacji podwojnych nawiasow kwadratowych
# tworzy nowy DataFrame zawierający tylko tę kolumnę.
# wybieramy zbiór kolumn poprzez podwójne nawiasy [[]]
df[['col_2']]

        col_2
first      12
second     12

In [ ]:
# sprawdzajac typ pojedynczej kolumny otrzymamy typ dataframe

type(df[['col_1']])

pandas.core.frame.DataFrame

In [ ]:
# nadpisanie nazw kolumn w serii obiekcie dataframe
df.columns = ['a' , 'b' ,  'sprzedaz_grudzien'   ]
df

         a   b  sprzedaz_grudzien
first   10  12                 13
second  23  12                 10

In [ ]:
# wypisanie wartosci kolumny czyli obiektu series
df.b
print(type(df.b))

<class 'pandas.core.series.Series'>

In [ ]:
# wycinanie 3 kolumny
df.sprzedaz_grudzien

first     13
second    10
Name: sprzedaz_grudzien, dtype: int64

In [ ]:
type(df.sprzedaz_grudzien)

pandas.core.series.Series

In [ ]:
# dodanie kolumny nazwa = przypisujemy wartosci
# (suma kolumn)
df['d'] = df.a + df.b

In [ ]:
df

         a   b  sprzedaz_grudzien   d
first   10  12                 13  22
second  23  12                 10  35

# dwie inne metody do wycinania iloc , oraz loc

In [ ]:
# loc pozwala wycinac obiekty po nazwach
# WYCIENCIE WIERSZA
df.loc['first']

a                    10
b                    12
sprzedaz_grudzien    13
d                    22
Name: first, dtype: int64

In [ ]:
# WYCIECIE elemntu KOLUMNY metoda loc
df.loc['first' , 'b'] # 12

np.int64(12)

In [ ]:
# tabela danych
df = pd.DataFrame(data=[[10,12,13] , [23 ,12 ,10]] , index = ['first' , 'second' ] , columns=['col_1' ,'col_2' ,'col_3' ])
df

        col_1  col_2  col_3
first      10     12     13
second     23     12     10

In [ ]:
# Wyciecie calej kolumny loc
df.loc[: , 'col_2']

first     12
second    12
Name: col_2, dtype: int64

In [ ]:
# iloc wyciananie wierszy po indeksach poczwaszy od zera 0
df.iloc[0]

a                    10
b                    12
sprzedaz_grudzien    13
d                    22
Name: first, dtype: int64

In [ ]:
# wyciagniecie elementu z tabeli poprzez iloc
df.iloc[1,2]

np.int64(10)