<a href="https://colab.research.google.com/github/Kornel1156/Data-Science/blob/main/2_Pandas_Analiza_Danych/02_dane_gieldowe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Pandas
>Strona biblioteki: [https://pandas.pydata.org/](https://pandas.pydata.org/)  
>Dokumentacja: [https://pandas.pydata.org/pandas-docs/stable/](https://pandas.pydata.org/pandas-docs/stable/)
>
>Podstawowa biblioteka do analizy danych w języku Python.
>
>Aby zainstalować bibliotekę Pandas użyj polecenia poniżej:
```
pip install pandas
pip install yfinance
```
### Spis treści:
1. [Import Bibliotek](#a1)
2. [Załadowanie danych](#a2)
3. [Eksploracja danych](#a3)
4. [Selekcja kolumn](#a4)
5. [Selekcja wierszy](#a5)
6. [Obliczanie nowych kolumn](#a6)
7. [Filtrowanie danych](#a7)

### <a name='a1'></a> Import Bibliotek

In [3]:
import numpy as np
import pandas as pd

print(f'Numpy: {np.__version__}')
print(f'Pandas: {pd.__version__}')

Numpy: 2.0.2
Pandas: 2.2.2

### <a name='a2'></a> Załadowanie danych

In [7]:
# def fetch_financial_data(company='AMZN'):
#     """Pobiera dane dotyczące notowań spółek na giełdzie według symboli
#     na serwisie stooq.pl"""
#     import pandas_datareader.data as web
#     return web.DataReader(name=company, data_source='stooq')

# df = fetch_financial_data()
# df.info()

import yfinance as yf

def fetch_financial_data(company='AMZN'):
    """Pobiera dane dotyczące notowań spółki."""
    return yf.download(company)

df = fetch_financial_data()

df.info()

/tmp/ipykernel_845/2564616995.py:14: FutureWarning: YF.download() has changed argument auto_adjust default to True
  return yf.download(company)
[*********************100%***********************]  1 of 1 completed

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 24 entries, 2026-07-14 to 2026-08-14
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AMZN)   24 non-null     float64
 1   (High, AMZN)    24 non-null     float64
 2   (Low, AMZN)     24 non-null     float64
 3   (Open, AMZN)    24 non-null     float64
 4   (Volume, AMZN)  24 non-null     int64
dtypes: float64(4), int64(1)
memory usage: 1.1 KB

### <a name='a3'></a> Eksploracja danych

In [8]:
df

Price            Close        High         Low        Open     Volume
Ticker            AMZN        AMZN        AMZN        AMZN       AMZN
Date
2026-07-14  247.490005  248.559998  243.800003  245.550003   30108100
2026-07-15  254.960007  256.480011  249.750000  249.750000   45240600
2026-07-16  249.889999  258.079987  248.000000  255.119995   45343700
2026-07-17  247.229996  250.240005  243.589996  244.460007   43572400
2026-07-20  249.990005  252.889999  248.000000  248.759995   32406500
2026-07-21  247.550003  249.339996  246.419998  249.110001   27732100
2026-07-22  244.850006  248.449997  242.449997  248.270004   34112700
2026-07-23  233.660004  238.350006  232.050003  236.259995   47465300
2026-07-24  232.110001  234.949997  231.339996  234.380005   35017400
2026-07-27  231.389999  235.889999  230.990005  235.669998   34999500
2026-07-28  230.860001  233.110001  228.100006  232.850006   44521600
2026-07-29  226.649994  232.820007  226.160004  229.320007   44957500
2026-07-30  235.500000  239.820007  231.059998  233.350006  101839800
2026-07-31  271.579987  273.230011  262.010010  265.000000  129054800
2026-08-03  284.019989  287.200012  278.000000  278.290009   90830200
2026-08-04  277.420013  281.070007  275.820007  276.059998   69748100
2026-08-05  272.649994  282.790009  270.730011  281.589996   45119800
2026-08-06  272.260010  275.480011  271.059998  272.769989   30672900
2026-08-07  274.480011  278.309998  272.750000  272.869995   33861400
2026-08-10  278.089996  280.140015  273.600006  274.010010   35731900
2026-08-11  272.269989  278.839996  271.359985  278.690002   31895700
2026-08-12  267.279999  273.459991  267.100006  273.179993   29941100
2026-08-13  265.130005  269.579987  264.709991  267.239990   32106400
2026-08-14  264.070007  265.809998  263.350006  264.875000   11358800

In [ ]:
df.head()

In [16]:
# okreslenie ile chcemy wierszy ze szczytu
df.head(3)

Price            Close        High         Low        Open    Volume
Ticker            AMZN        AMZN        AMZN        AMZN      AMZN
Date
2026-07-14  247.490005  248.559998  243.800003  245.550003  30108100
2026-07-15  254.960007  256.480011  249.750000  249.750000  45240600
2026-07-16  249.889999  258.079987  248.000000  255.119995  45343700

In [18]:
# 5 ostatnich wierszy z tabeli
df.tail()

Price            Close        High         Low        Open    Volume
Ticker            AMZN        AMZN        AMZN        AMZN      AMZN
Date
2026-08-10  278.089996  280.140015  273.600006  274.010010  35731900
2026-08-11  272.269989  278.839996  271.359985  278.690002  31895700
2026-08-12  267.279999  273.459991  267.100006  273.179993  29941100
2026-08-13  265.130005  269.579987  264.709991  267.239990  32106400
2026-08-14  264.070007  265.809998  263.350006  264.875000  11358800

In [19]:
# 10 ostanich wierszy z tabeli
df.tail(10)

Price            Close        High         Low        Open    Volume
Ticker            AMZN        AMZN        AMZN        AMZN      AMZN
Date
2026-08-03  284.019989  287.200012  278.000000  278.290009  90830200
2026-08-04  277.420013  281.070007  275.820007  276.059998  69748100
2026-08-05  272.649994  282.790009  270.730011  281.589996  45119800
2026-08-06  272.260010  275.480011  271.059998  272.769989  30672900
2026-08-07  274.480011  278.309998  272.750000  272.869995  33861400
2026-08-10  278.089996  280.140015  273.600006  274.010010  35731900
2026-08-11  272.269989  278.839996  271.359985  278.690002  31895700
2026-08-12  267.279999  273.459991  267.100006  273.179993  29941100
2026-08-13  265.130005  269.579987  264.709991  267.239990  32106400
2026-08-14  264.070007  265.809998  263.350006  264.875000  11358800

In [30]:
# spłaszczenie kolumny w yfinance
df.columns = df.columns.get_level_values(0)

In [31]:
# wyświetlenie nazw kolumn
df.columns

Index(['close', 'high', 'low', 'open', 'volume'], dtype='object')

In [29]:
#
df.columns = [col.lower() for col in df.columns]
df.head()

                 close        high         low        open    volume
Date
2026-07-14  247.490005  248.559998  243.800003  245.550003  30108100
2026-07-15  254.960007  256.480011  249.750000  249.750000  45240600
2026-07-16  249.889999  258.079987  248.000000  255.119995  45343700
2026-07-17  247.229996  250.240005  243.589996  244.460007  43572400
2026-07-20  249.990005  252.889999  248.000000  248.759995  32406500

In [32]:
# przedstawienie paru statystyk dla danych tabeli
df.describe()

            close        high         low        open        volume
count   24.000000   24.000000   24.000000   24.000000  2.400000e+01
mean   255.474168  259.370419  253.008334  256.142708  4.615160e+07
std     17.937454   18.174538   17.525910   17.461646  2.645258e+07
min    226.649994  232.820007  226.160004  229.320007  1.135880e+07
25%    242.512505  246.292500  239.849998  242.410004  3.205372e+07
50%    252.475006  257.279999  248.875000  252.434998  3.537465e+07
75%    272.262505  276.187508  270.812508  272.947495  4.526638e+07
max    284.019989  287.200012  278.000000  281.589996  1.290548e+08

In [33]:
# przekształcenie danych dla lepszego czytania danych
df.describe().T

,count,mean,std,min,25%,50%,75%,max
close,24.0,2.554742e+02,1.793745e+01,2.266500e+02,2.425125e+02,2.524750e+02,2.722625e+02,2.840200e+02
high,24.0,2.593704e+02,1.817454e+01,2.328200e+02,2.462925e+02,2.572800e+02,2.761875e+02,2.872000e+02
low,24.0,2.530083e+02,1.752591e+01,2.261600e+02,2.398500e+02,2.488750e+02,2.708125e+02,2.780000e+02
open,24.0,2.561427e+02,1.746165e+01,2.293200e+02,2.424100e+02,2.524350e+02,2.729475e+02,2.815900e+02
volume,24.0,4.615160e+07,2.645258e+07,1.135880e+07,3.205372e+07,3.537465e+07,4.526638e+07,1.290548e+08

### <a name='a4'></a> Selekcja kolumn

In [34]:
# zmienna z pierwszymi 10 rekordami
df = df.head(10)
df

                 close        high         low        open    volume
Date
2026-07-14  247.490005  248.559998  243.800003  245.550003  30108100
2026-07-15  254.960007  256.480011  249.750000  249.750000  45240600
2026-07-16  249.889999  258.079987  248.000000  255.119995  45343700
2026-07-17  247.229996  250.240005  243.589996  244.460007  43572400
2026-07-20  249.990005  252.889999  248.000000  248.759995  32406500
2026-07-21  247.550003  249.339996  246.419998  249.110001  27732100
2026-07-22  244.850006  248.449997  242.449997  248.270004  34112700
2026-07-23  233.660004  238.350006  232.050003  236.259995  47465300
2026-07-24  232.110001  234.949997  231.339996  234.380005  35017400
2026-07-27  231.389999  235.889999  230.990005  235.669998  34999500

In [35]:
# nazwa kolumny i zostanie to wyciete jako obiekt typu Series
df['open']

Date
2026-07-14    245.550003
2026-07-15    249.750000
2026-07-16    255.119995
2026-07-17    244.460007
2026-07-20    248.759995
2026-07-21    249.110001
2026-07-22    248.270004
2026-07-23    236.259995
2026-07-24    234.380005
2026-07-27    235.669998
Name: open, dtype: float64

In [37]:
# po prostu nazwe kolumny jako obiekt series
df.open

Date
2026-07-14    245.550003
2026-07-15    249.750000
2026-07-16    255.119995
2026-07-17    244.460007
2026-07-20    248.759995
2026-07-21    249.110001
2026-07-22    248.270004
2026-07-23    236.259995
2026-07-24    234.380005
2026-07-27    235.669998
Name: open, dtype: float64

In [38]:
# wycinanie jako obiekt typu DataFrame w notacji podwojne kwadratowe nawiasy [[]]
df[['open']]

                  open
Date
2026-07-14  245.550003
2026-07-15  249.750000
2026-07-16  255.119995
2026-07-17  244.460007
2026-07-20  248.759995
2026-07-21  249.110001
2026-07-22  248.270004
2026-07-23  236.259995
2026-07-24  234.380005
2026-07-27  235.669998

In [ ]:
# Wycicecie kilku kolumn jako obiekty typu DataFrame
df[['open', 'close']]

In [42]:
# wycinanie kolumn  w metodzie iloc
# [indeksy(wiersze) : indeks kolumny który chcemy dostać ]
# pierwsza kolumna
df.iloc[:, 0]

Date
2026-07-15    254.960007
Name: close, dtype: float64

In [40]:
# jezeli chemy podac dwie kolumny to podajemy
# [indeksy(wiersze) : [liste ktorych kolumn chemy]]
df.iloc[:, [0, 3]]

                 close        open
Date
2026-07-14  247.490005  245.550003
2026-07-15  254.960007  249.750000
2026-07-16  249.889999  255.119995
2026-07-17  247.229996  244.460007
2026-07-20  249.990005  248.759995
2026-07-21  247.550003  249.110001
2026-07-22  244.850006  248.270004
2026-07-23  233.660004  236.259995
2026-07-24  232.110001  234.380005
2026-07-27  231.389999  235.669998

In [43]:
# [ wszystkie rekordy , oraz kolumny <3-5) ] ale uwaga bez 5 on sie nie zawiera czyli tylko 3 oraz 4 kolumny tylko
df.iloc[:, 3:5]

                  open    volume
Date
2026-07-14  245.550003  30108100
2026-07-15  249.750000  45240600
2026-07-16  255.119995  45343700
2026-07-17  244.460007  43572400
2026-07-20  248.759995  32406500
2026-07-21  249.110001  27732100
2026-07-22  248.270004  34112700
2026-07-23  236.259995  47465300
2026-07-24  234.380005  35017400
2026-07-27  235.669998  34999500

In [44]:
# ostatania kolumna
df.iloc[:, -1]

Date
2026-07-14    30108100
2026-07-15    45240600
2026-07-16    45343700
2026-07-17    43572400
2026-07-20    32406500
2026-07-21    27732100
2026-07-22    34112700
2026-07-23    47465300
2026-07-24    35017400
2026-07-27    34999500
Name: volume, dtype: int64

In [ ]:
df.iloc[:, [-1]]

In [ ]:
df.iloc[:, -3:]

### <a name='a5'></a>  Selekcja wierszy

In [ ]:
df

In [ ]:
df.iloc[0]

In [ ]:
df.iloc[:3]

In [ ]:
df

In [ ]:
df.loc['2019-12-10': '2019-12-02']

### <a name='a6'></a> Obliczanie nowych kolumn

In [ ]:
df = fetch_financial_data('UBER')
df.info()

In [ ]:
df.head()

In [ ]:
df.describe()

In [ ]:
df.head(3)

In [ ]:
df['Average'] = (df.Open + df.Close) / 2.0
df.head()

In [ ]:
df = df.sort_index()
df.head()

In [ ]:
df['Close_shift'] = df.Close.shift(1)
df.head()

In [ ]:
df['Daily_Change'] = df.Close / df.Close_shift - 1
df.head()

In [ ]:
del df['Daily Change']

In [ ]:
df.head()

In [ ]:
df.Daily_Change.min()

In [ ]:
df.Daily_Change.max()

In [ ]:
import seaborn as sns
sns.set()

df.Daily_Change.hist(bins=100)

In [ ]:
df.Close.plot()

### <a name='a7'></a> Filtrowanie danych

In [ ]:
df

In [ ]:
df_positive = df[df.Daily_Change > 0]
df_positive

In [ ]:
df_positive.Daily_Change.mean()

In [ ]:
 df_negative = df[df.Daily_Change < 0]
 df_negative

In [ ]:
 df_negative.Daily_Change.mean()

In [ ]:
df.Close == df.High

In [ ]:
df[df.Close == df.High]

In [ ]:
df[df.Close == df.Low]

In [ ]:
df.index > '2019-11-01'

In [ ]:
df[df.index > '2019-11-01']

In [ ]:
df[(df.index >= '2019-11-01') & (df.index < '2019-11-15')]

In [ ]:
df[(df.index == '2019-11-01') | (df.index == '2019-11-07')]

In [ ]:
df

In [ ]:
df[df.index.month == 5]

In [ ]:
df[df.index.day == 1]