<a href="https://colab.research.google.com/github/Kornel1156/Data-Science/blob/main/2_Pandas_Analiza_Danych/06_appstore_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Spis treści:
1. [import bibliotek](#a1)
2. [załadaowanie danych](#a2)
3. [preprocessing - przygotowanie danych](#a3)
4. [jak zbadac rozklad zmiennych](#a4)
5. [sprawdzenie braków w danych](#a5)

### <a name='a1'></a> import bibliotek

In [30]:
# import bibliotek
import pandas as pd
print(pd.__version__)

2.2.3

### <a name='a2'></a> załadaowanie danych

In [31]:
url = 'https://storage.googleapis.com/esmartdata-courses-files/ds-bootcamp/appstore_games.csv'
df_raw = pd.read_csv(url)
df_raw.head()

,URL,ID,Name,Subtitle,Icon URL,Average User Rating,User Rating Count,Price,In-app Purchases,Description,Developer,Age Rating,Languages,Size,Primary Genre,Genres,Original Release Date,Current Version Release Date
0,https://apps.apple.com/us/app/sudoku/id284921427,284921427,Sudoku,NaN,https://is2-ssl.mzstatic.com/image/thumb/Purpl...,4.0,3553.0,2.99,NaN,"Join over 21,000,000 of our fans and download ...",Mighty Mighty Good Games,4+,"DA, NL, EN, FI, FR, DE, IT, JA, KO, NB, PL, PT...",15853568.0,Games,"Games, Strategy, Puzzle",11/07/2008,30/05/2017
1,https://apps.apple.com/us/app/reversi/id284926400,284926400,Reversi,NaN,https://is4-ssl.mzstatic.com/image/thumb/Purpl...,3.5,284.0,1.99,NaN,"The classic game of Reversi, also known as Oth...",Kiss The Machine,4+,EN,12328960.0,Games,"Games, Strategy, Board",11/07/2008,17/05/2018
2,https://apps.apple.com/us/app/morocco/id284946595,284946595,Morocco,NaN,https://is5-ssl.mzstatic.com/image/thumb/Purpl...,3.0,8376.0,0.00,NaN,Play the classic strategy game Othello (also k...,Bayou Games,4+,EN,674816.0,Games,"Games, Board, Strategy",11/07/2008,5/09/2017
3,https://apps.apple.com/us/app/sudoku-free/id28...,285755462,Sudoku (Free),NaN,https://is3-ssl.mzstatic.com/image/thumb/Purpl...,3.5,190394.0,0.00,NaN,"Top 100 free app for over a year.\nRated ""Best...",Mighty Mighty Good Games,4+,"DA, NL, EN, FI, FR, DE, IT, JA, KO, NB, PL, PT...",21552128.0,Games,"Games, Strategy, Puzzle",23/07/2008,30/05/2017
4,https://apps.apple.com/us/app/senet-deluxe/id2...,285831220,Senet Deluxe,NaN,https://is1-ssl.mzstatic.com/image/thumb/Purpl...,3.5,28.0,2.99,NaN,"""Senet Deluxe - The Ancient Game of Life and A...",RoGame Software,4+,"DA, NL, EN, FR, DE, EL, IT, JA, KO, NO, PT, RU...",34689024.0,Games,"Games, Strategy, Board, Education",18/07/2008,22/07/2018

### <a name='a3'></a> preprocessing - przygotowanie danych

In [32]:
# sprawdzenie jakie mamy kolumny
df_raw.columns

Index(['URL', 'ID', 'Name', 'Subtitle', 'Icon URL', 'Average User Rating',
       'User Rating Count', 'Price', 'In-app Purchases', 'Description',
       'Developer', 'Age Rating', 'Languages', 'Size', 'Primary Genre',
       'Genres', 'Original Release Date', 'Current Version Release Date'],
      dtype='object')

In [33]:
# kopia obiektu aby nie brudzić obiektu głownego z danymi
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17007 entries, 0 to 17006
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   URL                           17007 non-null  object
 1   ID                            17007 non-null  int64
 2   Name                          17007 non-null  object
 3   Subtitle                      5261 non-null   object
 4   Icon URL                      17007 non-null  object
 5   Average User Rating           7561 non-null   float64
 6   User Rating Count             7561 non-null   float64
 7   Price                         16983 non-null  float64
 8   In-app Purchases              7683 non-null   object
 9   Description                   17007 non-null  object
 10  Developer                     17007 non-null  object
 11  Age Rating                    17007 non-null  object
 12  Languages                     16947 non-null  object
 13  Size                          17006 non-null  float64
 14  Primary Genre                 17007 non-null  object
 15  Genres                        17007 non-null  object
 16  Original Release Date         17007 non-null  object
 17  Current Version Release Date  17007 non-null  object
dtypes: float64(4), int64(1), object(13)
memory usage: 2.3+ MB

In [34]:
# usuniecie kolumn ktore nas nie interesuja poprzez parametr drop
df = df.drop(columns=['URL' , 'Icon URL' , 'Subtitle' , 'Description' , 'In-app Purchases'])
# po nieuwzglednieniu kilku kolumn
df.head()

,ID,Name,Average User Rating,User Rating Count,Price,Developer,Age Rating,Languages,Size,Primary Genre,Genres,Original Release Date,Current Version Release Date
0,284921427,Sudoku,4.0,3553.0,2.99,Mighty Mighty Good Games,4+,"DA, NL, EN, FI, FR, DE, IT, JA, KO, NB, PL, PT...",15853568.0,Games,"Games, Strategy, Puzzle",11/07/2008,30/05/2017
1,284926400,Reversi,3.5,284.0,1.99,Kiss The Machine,4+,EN,12328960.0,Games,"Games, Strategy, Board",11/07/2008,17/05/2018
2,284946595,Morocco,3.0,8376.0,0.00,Bayou Games,4+,EN,674816.0,Games,"Games, Board, Strategy",11/07/2008,5/09/2017
3,285755462,Sudoku (Free),3.5,190394.0,0.00,Mighty Mighty Good Games,4+,"DA, NL, EN, FI, FR, DE, IT, JA, KO, NB, PL, PT...",21552128.0,Games,"Games, Strategy, Puzzle",23/07/2008,30/05/2017
4,285831220,Senet Deluxe,3.5,28.0,2.99,RoGame Software,4+,"DA, NL, EN, FR, DE, EL, IT, JA, KO, NO, PT, RU...",34689024.0,Games,"Games, Strategy, Board, Education",18/07/2008,22/07/2018

In [35]:
# ustawiamy indeksy rekordow jako osobne kolumny
df = df.set_index('ID')
df.head()

,Name,Average User Rating,User Rating Count,Price,Developer,Age Rating,Languages,Size,Primary Genre,Genres,Original Release Date,Current Version Release Date
ID,,,,,,,,,,,,
284921427,Sudoku,4.0,3553.0,2.99,Mighty Mighty Good Games,4+,"DA, NL, EN, FI, FR, DE, IT, JA, KO, NB, PL, PT...",15853568.0,Games,"Games, Strategy, Puzzle",11/07/2008,30/05/2017
284926400,Reversi,3.5,284.0,1.99,Kiss The Machine,4+,EN,12328960.0,Games,"Games, Strategy, Board",11/07/2008,17/05/2018
284946595,Morocco,3.0,8376.0,0.00,Bayou Games,4+,EN,674816.0,Games,"Games, Board, Strategy",11/07/2008,5/09/2017
285755462,Sudoku (Free),3.5,190394.0,0.00,Mighty Mighty Good Games,4+,"DA, NL, EN, FI, FR, DE, IT, JA, KO, NB, PL, PT...",21552128.0,Games,"Games, Strategy, Puzzle",23/07/2008,30/05/2017
285831220,Senet Deluxe,3.5,28.0,2.99,RoGame Software,4+,"DA, NL, EN, FR, DE, EL, IT, JA, KO, NO, PT, RU...",34689024.0,Games,"Games, Strategy, Board, Education",18/07/2008,22/07/2018

In [36]:
# statystyki danych których ilosc kolumn jest mniejsza niz rzeczywista ilosc poniewaz zostały policzone tylko dla kolumn z danymi o typie flaot albo int alob double
df.describe()

       Average User Rating  User Rating Count         Price          Size
count          7561.000000       7.561000e+03  16983.000000  1.700600e+04
mean              4.060905       3.306531e+03      0.813419  1.157064e+08
std               0.751428       4.232256e+04      7.835732  2.036477e+08
min               1.000000       5.000000e+00      0.000000  5.132800e+04
25%               3.500000       1.200000e+01      0.000000  2.295014e+07
50%               4.500000       4.600000e+01      0.000000  5.676895e+07
75%               4.500000       3.090000e+02      0.000000  1.330271e+08
max               5.000000       3.032734e+06    179.990000  4.005591e+09

In [37]:
# zmiana kolumn z wierszami dla czytelnosi
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Average User Rating,7561.0,4.060905e+00,7.514275e-01,1.0,3.5,4.5,4.5,5.000000e+00
User Rating Count,7561.0,3.306531e+03,4.232256e+04,5.0,12.0,46.0,309.0,3.032734e+06
Price,16983.0,8.134187e-01,7.835732e+00,0.0,0.0,0.0,0.0,1.799900e+02
Size,17006.0,1.157064e+08,2.036477e+08,51328.0,22950144.0,56768954.0,133027072.0,4.005591e+09

In [38]:
# statystyki wybranych danych czyli zamiast statystyk dla kolumn z danymi o typie float oraz int jeszcze mamy dla danych z typem object
df.describe(include=['object'])

,Name,Developer,Age Rating,Languages,Primary Genre,Genres,Original Release Date,Current Version Release Date
count,17007,17007,17007,16947,17007,17007,17007,17007
unique,16847,8693,4,990,21,1004,3084,2512
top,10-in-1 Board Games BA.net,Tapps Tecnologia da Informa\xe7\xe3o Ltda.,4+,EN,Games,"Games, Strategy, Puzzle",2/09/2016,1/08/2019
freq,2,123,11806,12467,16286,778,75,118

In [39]:
# zmiana werszy z kolumną
df.describe(include=['object']).T

,count,unique,top,freq
Name,17007,16847,10-in-1 Board Games BA.net,2
Developer,17007,8693,Tapps Tecnologia da Informa\xe7\xe3o Ltda.,123
Age Rating,17007,4,4+,11806
Languages,16947,990,EN,12467
Primary Genre,17007,21,Games,16286
Genres,17007,1004,"Games, Strategy, Puzzle",778
Original Release Date,17007,3084,2/09/2016,75
Current Version Release Date,17007,2512,1/08/2019,118

In [40]:
# ustandaryzowanie danych które wystepuja czyli:
# 1. spacje znajdujace sie w nazwie zastąpić podkreślnikiem
# 2. ustandaryzujemy wszytkie literny jakiekolwiek duze z slowie damy na male
df.columns

Index(['Name', 'Average User Rating', 'User Rating Count', 'Price',
       'Developer', 'Age Rating', 'Languages', 'Size', 'Primary Genre',
       'Genres', 'Original Release Date', 'Current Version Release Date'],
      dtype='object')

In [43]:
# ustandaryzowanie nazw kolumn
df.columns = [col.lower().replace(' ' , '_') for col in df.columns]
df.head()

,name,average_user_rating,user_rating_count,price,developer,age_rating,languages,size,primary_genre,genres,original_release_date,current_version_release_date
ID,,,,,,,,,,,,
284921427,Sudoku,4.0,3553.0,2.99,Mighty Mighty Good Games,4+,"DA, NL, EN, FI, FR, DE, IT, JA, KO, NB, PL, PT...",15853568.0,Games,"Games, Strategy, Puzzle",11/07/2008,30/05/2017
284926400,Reversi,3.5,284.0,1.99,Kiss The Machine,4+,EN,12328960.0,Games,"Games, Strategy, Board",11/07/2008,17/05/2018
284946595,Morocco,3.0,8376.0,0.00,Bayou Games,4+,EN,674816.0,Games,"Games, Board, Strategy",11/07/2008,5/09/2017
285755462,Sudoku (Free),3.5,190394.0,0.00,Mighty Mighty Good Games,4+,"DA, NL, EN, FI, FR, DE, IT, JA, KO, NB, PL, PT...",21552128.0,Games,"Games, Strategy, Puzzle",23/07/2008,30/05/2017
285831220,Senet Deluxe,3.5,28.0,2.99,RoGame Software,4+,"DA, NL, EN, FR, DE, EL, IT, JA, KO, NO, PT, RU...",34689024.0,Games,"Games, Strategy, Board, Education",18/07/2008,22/07/2018

In [45]:
# dzieki podłagom mamy szybkie wyszukiwanie nazwy takiej kolumny poprzez podpowiedz
df.average_user_rating

ID
284921427     4.0
284926400     3.5
284946595     3.0
285755462     3.5
285831220     3.5
             ...
1474626442    NaN
1474919257    NaN
1474962324    NaN
1474963671    NaN
1475076711    NaN
Name: average_user_rating, Length: 17007, dtype: float64

### <a name='a4'></a> jak zbadac rozklad zmiennych

### <a name='a5'></a> sprawdzenie braków w danych